### ISSUE TITLE
Hyprgrass doesn't build on latest Hyprland commit

### ISSUE THREAD

**Issue by matt1432** [horriblename/hyprgrass#50] opened 2023-10-15 00:13 UTC
```
> /nix/store/6pdsf2nfyniddz8yk7xxzmlc98zg3dkb-hyprland-0.30.0+date=2023-10-14_261c594-dev/include/hyprland/src/plugins/PluginAPI.hpp:276:12: note: the macro 'GIT_COMMIT_HASH' had not yet been defined
       > In file included from /nix/store/6pdsf2nfyniddz8yk7xxzmlc98zg3dkb-hyprland-0.30.0+date=2023-10-14_261c594-dev/include/hyprland/src/macros.hpp:17,
       >                  from /nix/store/6pdsf2nfyniddz8yk7xxzmlc98zg3dkb-hyprland-0.30.0+date=2023-10-14_261c594-dev/include/hyprland/src/helpers/Vector2D.hpp:5,
       >                  from /nix/store/6pdsf2nfyniddz8yk7xxzmlc98zg3dkb-hyprland-0.30.0+date=2023-10-14_261c594-dev/include/hyprland/src/helpers/MiscFunctions.hpp:6,
       >                  from /nix/store/6pdsf2nfyniddz8yk7xxzmlc98zg3dkb-hyprland-0.30.0+date=2023-10-14_261c594-dev/include/hyprland/src/debug/Log.hpp:8,
       >                  from ../src/GestureManager.hpp:4:
       > /nix/store/6pdsf2nfyniddz8yk7xxzmlc98zg3dkb-hyprland-0.30.0+date=2023-10-14_261c594-dev/include/hyprland/src/version.h:2: note: it was later defined here
       >     2 | #define GIT_COMMIT_HASH    "261c594458fec8bc64136eebf7c7e4e5ab421907"
       >       |
       > ninja: build stopped: subcommand failed.
```

**Comment by crimist** [comment] 2023-10-15 05:33
Hyprland is failing to build - not hyprgrass. Looks like it's probably an upstream issue caused by https://github.com/hyprwm/Hyprland/pull/3545#issuecomment-1763164692

**Comment by matt1432** [comment] 2023-10-15 05:43
huh, it said hyprgrass derivation failed to build so I assumed it was the reason. Good to know, thank you

**Comment by horriblename** [comment] 2023-10-15 12:03
fixed in https://github.com/hyprwm/Hyprland/pull/3571

**Closed by horriblename** 2023-10-15 12:03 UTC
