### ISSUE TITLE
Using fn+to increase brightness will automatically execute all the shortcut settings of the touch plugin once

### ISSUE THREAD

**Issue by 0a00** [horriblename/hyprgrass#77] opened 2024-01-10 09:55 UTC
Using fn+to increase brightness will automatically execute all the shortcut settings of the touch plugin once
![图片](https://github.com/horriblename/hyprgrass/assets/59482058/a471f11e-9c16-4497-8086-86811b661db8)
![图片](https://github.com/horriblename/hyprgrass/assets/59482058/95b7dca0-d091-4c37-8145-a5b189924771)
![图片](https://github.com/horriblename/hyprgrass/assets/59482058/82272a0f-0234-4e49-b55c-4da58850fef0)
After pressing Binde =, XF86Monbrightnessup, Exec, LightCtl Up, all the shortcut key functions of touch settings will be executed again

**Comment by horriblename** [comment] 2024-01-11 23:35
can't repro, what version of hyprland and hyprgrass?

**Comment by 0a00** [comment] 2024-01-12 05:42
![图片](https://github.com/horriblename/hyprgrass/assets/59482058/de0be3de-6833-47e0-bfa7-e0e60b70afd9)

**Comment by 0a00** [comment] 2024-01-12 05:46
In my case FN + F 4 is a shortcut to increase brightness, which is only caused by pressing FN + f 4. Taking exec of FN + f 4 alone does not cause this problem

**Comment by horriblename** [comment] 2024-01-12 16:56
does this affect other keys like the raise volume one? or just raise brightness? I don't have raise brightness so I cant test that

**Comment by 0a00** [comment] 2024-01-12 17:24
Because my increased volume is fn+f4, I tested that this only occurs when I press fn+f4

**Comment by rubiigen** [comment] 2024-02-05 11:22
I can reproduce this issue on my laptop using XF86MonBrigtnessUp

**Comment by horriblename** [comment] 2024-02-06 18:53
This bug is most likely in Hyprland, not hyprgrass. I'll keep this open for now since it is somewhat my fault for abusing the bind system. If anyone wants to take a look, it's probably a problem in the KeybindManager

**Comment by rubiigen** [comment] 2024-02-07 14:18
if its most likely a hyprland issue, then wouldnt it make sense to also make an issue there. Also if it helps i noticed this issue seems to effect d:u and u:d gestures the most (in my case full screen and open terminal)

**Comment by horriblename** [comment] 2024-02-08 06:28
yes someone should report it upstream. but first test and see if it still happens when hyprgrass isn't loaded.

If you followed the instructions in the README and override inputs.hyprland to your own, bumping flake.lock wouldn't help here

**Comment by rubiigen** [comment] 2024-02-08 22:10
when hyprgrass isnt loaded it doesn't occur

**Comment by rubiigen** [comment] 2024-02-08 22:12
@horriblename another thing, i commented out the override and the issue stopped occuring. though now i get an annoying mismatched hyprland version notification

**Comment by rubiigen** [comment] 2024-02-23 11:21
still an issue btw

**Comment by EddyTheDood** [comment] 2024-03-04 19:25
I'm having the same issue on my Surface Pro 8 when I remove the pen. I'm running the 6.7.6-arch1-1-surface kernel and Hyprland 0.35.0. I'll try to look into it in a week or so; does anybody have any ideas as to what specifically is causing this?

**Comment by rubiigen** [comment] 2024-03-04 22:16
This is a weird issue for me, seems to come and go

**Comment by horriblename** [comment] 2024-03-16 13:29
workaround #97 allows to use a different keybind list, separate from Hyprland's, which should in theory prevent the bug

**Comment by horriblename** [comment] 2024-03-16 21:17
keywords in hyprlang looks promising, long term it'd be better to move to that and use completely separate bind list, if the above "fix" works I'll start moving to keywords:

```
plugins:touch_gesture{
  bind = , swipe:3:d, exec, foo
  bind = , edge:u:d, exec, bar
}
```

**Comment by horriblename** [comment] 2024-06-10 22:46
should be fixed (with `hyprgrass-bind` keyword) by now

**Closed by horriblename** 2024-06-10 22:46 UTC
Labels: bug, help wanted
